### ISSUE TITLE
[FEATURE] Tutorial with rpi and without TTL

### ISSUE THREAD

**Issue by jlssmt** [mmakaay/esphome-xiaomi_bslamp2#28]
**Is your feature request related to a problem? Please describe.**
I have a raspberrypi and no TTL adapter. I'm also on iobroker instead of home-assistant.
I'm not very familiar with serial flashing firmwares.
I think there are a lot of people out there with the same requirements than me.
Is there any chance to modify the tutorial how to flash with rpi + female-to-male-wires? I also need support for compiling the firmware or is it also possible to simply flash tasmota?

**Describe the solution you'd like**
Open the lamp, connect the rpi directly via female-to-male-wires with the lamp, flash.

**Describe alternatives you've considered**
Buying a FTDI adapter which will never be used again.

**Comment by mmakaay** [comment]
How are you going to connect the lamp to iobroker? MQTT is an option, but the hass-mqtt integration in iobroker does only support switch and sensor. Note that the ESPHome firmware does not implement the original LAN control protocol. 
Not saying that it is not possible, but just a heads up to check what is possible in your system before replacing the firmware.

For flashing: what about installing HassOS on an SDcard and use its ESPHome add-on? 

Another option could be to run raspbian and install ESPHome for command line use. This would also provide you with the option to backup and restore the original firmware using esptool. 
In the flashing docs, there's also information about flashing from the command line using esptool. 

I don't thi
